### ISSUE TITLE
Freeze on hitting any buttons on home screen.

### ISSUE THREAD

**Issue by perryprog** [germantownacademySOS/ios2#1]
Pressing any button on the home screen freezes the app. It seems that there is no more outlets....
I didn't change anything, so @sfraser please go and fix it 😄

**Comment by sfraser** [comment]
I can't reproduce! Can you double check this is happening on the latest build?

**Comment by perryprog** [comment]
Magically fixed itself. I blame pandas.


![](http://i.giphy.com/14aUO0Mf7dWDXW.gif)

**Comment by sfraser** [comment]
yay pandas
